name: irrigation-analysis
channels:
  - conda-forge
  - nodefaults
dependencies:
  - requests
  - xarray
  - pandas
  - numpy
  - matplotlib
  - cartopy
  - dask
  - netcdf4
  - tqdm
  - pytest
  - pip:
    - researchpy
